name: microkernel_workspace

packages:
  - "packages/**"
  - "plugins/**"
  - "plugins/auth"
  - "plugins/core_services"
  - "plugins/balance"

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run Flutter analyze for all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  test:
    run: melos exec --fail-fast -- flutter test
    description: Run tests for all packages
    
  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages
    
  clean:
    run: melos exec -- flutter clean
    description: Clean all packages
