name: microkernel_demo
environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  melos: ^7.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  
  # Paquetes locales
  microkernel_core:
    path: packages/microkernel_core
  core_models:
    path: packages/core_models
    
  # Plugins
  auth_plugin:
    path: plugins/auth
  core_services:
    path: plugins/core_services
  balance_plugin:
    path: plugins/balance

flutter:
  uses-material-design: true