name: microkernel_demo
environment:
  sdk: ">=3.9.0 <4.0.0"
dev_dependencies:
  melos: ^7.1.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  microkernel_core:
    path: packages/microkernel_core
  auth_plugin:
    path: plugins/auth
  core_services:
    path: plugins/core_services

flutter:
  uses-material-design: true