name: microkernel_core
description: Core components for microkernel architecture
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter