name: core_models
description: Contratos, eventos y modelos compartidos para el microkernel
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
